### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by wmdietl**
All contributors (including in PRs):
@topnessman 
@jyluo 
@AndrewShf 
@xingweitian 
@baoruiz 
@lnsun 

Please comment that you approve.

### CODE REVIEW

**Comment by AndrewShf** [comment]
I agree with this change.

**Comment by lnsun** [comment]
I agree with this change.

**Comment by baoruiz** [comment]
Change looks good to me!

**Comment by jyluo** [comment]
I approve this change!

**Comment by wmdietl** [comment]
Thanks, everyone!

**Pull request merged**
